/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SettingsIndexRouteImport } from "./routes/settings/index";
import { Route as PostsIndexRouteImport } from "./routes/posts/index";
import { Route as CompsIndexRouteImport } from "./routes/comps/index";
import { Route as AboutIndexRouteImport } from "./routes/about/index";
import { Route as PostsPostIdRouteImport } from "./routes/posts/$postId";
import { Route as SettingsBaseIndexRouteImport } from "./routes/settings/base/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => rootRouteImport,
} as any);
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: "/posts/",
  path: "/posts/",
  getParentRoute: () => rootRouteImport,
} as any);
const CompsIndexRoute = CompsIndexRouteImport.update({
  id: "/comps/",
  path: "/comps/",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: "/about/",
  path: "/about/",
  getParentRoute: () => rootRouteImport,
} as any);
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: "/posts/$postId",
  path: "/posts/$postId",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsBaseIndexRoute = SettingsBaseIndexRouteImport.update({
  id: "/settings/base/",
  path: "/settings/base/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/posts/$postId": typeof PostsPostIdRoute;
  "/about/": typeof AboutIndexRoute;
  "/comps/": typeof CompsIndexRoute;
  "/posts/": typeof PostsIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/settings/base/": typeof SettingsBaseIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/posts/$postId": typeof PostsPostIdRoute;
  "/about": typeof AboutIndexRoute;
  "/comps": typeof CompsIndexRoute;
  "/posts": typeof PostsIndexRoute;
  "/settings": typeof SettingsIndexRoute;
  "/settings/base": typeof SettingsBaseIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/posts/$postId": typeof PostsPostIdRoute;
  "/about/": typeof AboutIndexRoute;
  "/comps/": typeof CompsIndexRoute;
  "/posts/": typeof PostsIndexRoute;
  "/settings/": typeof SettingsIndexRoute;
  "/settings/base/": typeof SettingsBaseIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/posts/$postId"
    | "/about/"
    | "/comps/"
    | "/posts/"
    | "/settings/"
    | "/settings/base/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/posts/$postId"
    | "/about"
    | "/comps"
    | "/posts"
    | "/settings"
    | "/settings/base";
  id:
    | "__root__"
    | "/"
    | "/posts/$postId"
    | "/about/"
    | "/comps/"
    | "/posts/"
    | "/settings/"
    | "/settings/base/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  PostsPostIdRoute: typeof PostsPostIdRoute;
  AboutIndexRoute: typeof AboutIndexRoute;
  CompsIndexRoute: typeof CompsIndexRoute;
  PostsIndexRoute: typeof PostsIndexRoute;
  SettingsIndexRoute: typeof SettingsIndexRoute;
  SettingsBaseIndexRoute: typeof SettingsBaseIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/": {
      id: "/settings/";
      path: "/settings";
      fullPath: "/settings/";
      preLoaderRoute: typeof SettingsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/posts/": {
      id: "/posts/";
      path: "/posts";
      fullPath: "/posts/";
      preLoaderRoute: typeof PostsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/comps/": {
      id: "/comps/";
      path: "/comps";
      fullPath: "/comps/";
      preLoaderRoute: typeof CompsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about/": {
      id: "/about/";
      path: "/about";
      fullPath: "/about/";
      preLoaderRoute: typeof AboutIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/posts/$postId": {
      id: "/posts/$postId";
      path: "/posts/$postId";
      fullPath: "/posts/$postId";
      preLoaderRoute: typeof PostsPostIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/base/": {
      id: "/settings/base/";
      path: "/settings/base";
      fullPath: "/settings/base/";
      preLoaderRoute: typeof SettingsBaseIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  CompsIndexRoute: CompsIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsBaseIndexRoute: SettingsBaseIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
